spring:
  application:
    name: order-service
    #开启热部署
  devtools:
    remote:
      restart:
        enabled: true
#server:
#  port: 8201


feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202        
        
                    
